### PR TITLE
Noterror fixes #7

### LINKED ISSUE #7: Error Handling with C. A basic but robust error handling is required.
- make changes in c/noterror folder based on the task in c/README.md
- use PR template in docs/ when creating a PR

### PR DESCRIPTION
**Pull request by jeevanghimire**
## Describe your changes

Implemented a robust error-handling mechanism for file operations, memory allocation, and network communication in C. This includes centralized error codes, logging errors into a file (`error_log.txt`), and gracefully exiting the program during critical errors like memory allocation failure. A macro was used to simplify error handling, capturing function names and line numbers for better traceability.

## Context
This PR addresses the need for structured error handling in the program, allowing for better debugging, logging, and graceful exits during critical failures such as memory allocation errors.

Closes #7 

## Checklist before requesting a review
- [x] If it is a core feature, I have added thorough tests
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have only one commit (if not, squash them into one commit)
- [x] This PR is not a duplicate

---

This includes all the required tick marks as requested!

### CODE REVIEW

**Comment by axyut** [comment]
it shows 2 previous commits in this PR, next time create a local branch when you've pulled from the updated repo to only have a commit related to the issue.
Remove the Introduction section after the summary (not the one in the top) in the `noterror/README.md` file.

**Comment by axyut** [comment]
you have exactly done what i requested not to do.
look at line 45 at `noterror/README.md` copy the line and paste it at top in Introduction section.

**Comment by jeevanghimire** [comment]
Ohh Sorry I mistakly remove from top section I will fix it and commit the changes !!

**Comment by jeevanghimire** [comment]
That should do the job now !

**Pull request merged**
